# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

src/CMakeFiles/cli_depend.dir/client.cpp.o: src/client.cpp
src/CMakeFiles/cli_depend.dir/client.cpp.o: src/client.h

